# 💡 Pandas Practice Exercise 1: Solutions & Walkthroughs

This notebook contains **complete, verified solutions** for all 20 problems in `02_pandas_exercise_1.ipynb`.
Every code cell is pre-executed with visible outputs for instant verification.

### Problem 1: Import Pandas and Check Version

Import pandas with the alias `pd` and numpy as `np`. Print their installed versions.

In [1]:
import pandas as pd
import numpy as np

print(f"Pandas version: {pd.__version__}")
print(f"NumPy version:  {np.__version__}")

Pandas version: 3.0.6
NumPy version:  2.5.3

### Problem 2: Create a Series with Custom Index

Create a `pd.Series` containing the populations (in millions) of five cities: `{'Tokyo': 37.4, 'Delhi': 29.3, 'Shanghai': 26.3, 'Sao Paulo': 21.8, 'Mexico City': 21.6}`. Give the Series the name `'Population_M'`.

In [2]:
cities = ['Tokyo', 'Delhi', 'Shanghai', 'Sao Paulo', 'Mexico City']
populations = [37.4, 29.3, 26.3, 21.8, 21.6]

pop_series = pd.Series(populations, index=cities, name='Population_M')
print(pop_series)
print(f"\nTokyo Population: {pop_series['Tokyo']}M")

Tokyo          37.4
Delhi          29.3
Shanghai       26.3
Sao Paulo      21.8
Mexico City    21.6
Name: Population_M, dtype: float64

Tokyo Population: 37.4M

### Problem 3: Create a DataFrame from a Dictionary

Create a DataFrame `students_df` representing 5 students with the following columns:
- `'Name'`: `['Alice', 'Bob', 'Charlie', 'Diana', 'Evan']`
- `'Age'`: `[20, 22, 21, 23, 20]`
- `'Major'`: `['CS', 'Math', 'Physics', 'CS', 'Biology']`
- `'GPA'`: `[3.8, 3.2, 3.9, 2.9, 3.5]`
- `'Passed'`: `[True, True, True, False, True]`

In [3]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'Diana', 'Evan'],
    'Age': [20, 22, 21, 23, 20],
    'Major': ['CS', 'Math', 'Physics', 'CS', 'Biology'],
    'GPA': [3.8, 3.2, 3.9, 2.9, 3.5],
    'Passed': [True, True, True, False, True]
}

students_df = pd.DataFrame(data)
display(students_df)

      Name  Age    Major  GPA  Passed
0    Alice   20       CS  3.8    True
1      Bob   22     Math  3.2    True
2  Charlie   21  Physics  3.9    True
3    Diana   23       CS  2.9   False
4     Evan   20  Biology  3.5    True

### Problem 4: Inspect DataFrame Dimensions and Data Types

Using `students_df`, print:
1. The total number of rows and columns (shape)
2. The column names
3. The data type (`dtype`) of each column
4. A summary of non-null counts and memory using `.info()`

In [4]:
print(f"Shape (rows, cols): {students_df.shape}")
print(f"Columns: {list(students_df.columns)}")
print("\nColumn Data Types:")
print(students_df.dtypes)
print("\nDataFrame Info:")
students_df.info()

Shape (rows, cols): (5, 5)
Columns: ['Name', 'Age', 'Major', 'GPA', 'Passed']

Column Data Types:
Name          str
Age         int64
Major         str
GPA       float64
Passed       bool
dtype: object

DataFrame Info:
<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      str
 1   Age     5 non-null      int64
 2   Major   5 non-null      str
 3   GPA     5 non-null      float64
 4   Passed  5 non-null      bool
dtypes: bool(1), float64(1), int64(1), str(2)
memory usage: 297.0 bytes

### Problem 5: Series vs DataFrame Column Selection

1. Extract the `'GPA'` column as a 1D `Series` and store it in `gpa_series`.
2. Extract the `'Name'` and `'GPA'` columns as a 2D `DataFrame` and store it in `name_gpa_df`.
3. Print the types of both variables.

In [5]:
gpa_series = students_df['GPA']
name_gpa_df = students_df[['Name', 'GPA']]

print(f"Type of gpa_series:  {type(gpa_series)}")
print(f"Type of name_gpa_df: {type(name_gpa_df)}")
display(name_gpa_df)

Type of gpa_series:  <class 'pandas.Series'>
Type of name_gpa_df: <class 'pandas.DataFrame'>

      Name  GPA
0    Alice  3.8
1      Bob  3.2
2  Charlie  3.9
3    Diana  2.9
4     Evan  3.5

### Problem 6: Positional Slicing with .iloc

Using `students_df`:
1. Select the first 3 rows and the first 3 columns using `.iloc`.
2. Select the very last row using negative integer indexing.

In [6]:
# 1. First 3 rows and first 3 columns
subset_iloc = students_df.iloc[0:3, 0:3]
print("First 3 rows and 3 columns:")
display(subset_iloc)

# 2. Last row
print("\nLast row:")
print(students_df.iloc[-1])

First 3 rows and 3 columns:

      Name  Age    Major
0    Alice   20       CS
1      Bob   22     Math
2  Charlie   21  Physics

Last row:
Name         Evan
Age            20
Major     Biology
GPA           3.5
Passed       True
Name: 4, dtype: object

### Problem 7: Label-Based Selection with .loc

1. Create a new DataFrame `df_named` by setting `'Name'` as the index of `students_df`.
2. Use `.loc` to retrieve the `'Major'` and `'GPA'` for `'Charlie'`.
3. Slice from `'Bob'` to `'Diana'` (inclusive) for all columns.

In [7]:
df_named = students_df.set_index('Name')

# Charlie's record
charlie_info = df_named.loc['Charlie', ['Major', 'GPA']]
print("Charlie's Major and GPA:")
print(charlie_info)

# Slice from Bob to Diana
print("\nSlice from Bob to Diana (inclusive):")
display(df_named.loc['Bob':'Diana'])

Charlie's Major and GPA:
Major    Physics
GPA          3.9
Name: Charlie, dtype: object

Slice from Bob to Diana (inclusive):

         Age    Major  GPA  Passed
Name
Bob       22     Math  3.2    True
Charlie   21  Physics  3.9    True
Diana     23       CS  2.9   False

### Problem 8: Single Condition Filtering

Filter `students_df` to find all students who have a `'GPA'` strictly greater than `3.4`.

In [8]:
high_achievers = students_df[students_df['GPA'] > 3.4]
display(high_achievers)

      Name  Age    Major  GPA  Passed
0    Alice   20       CS  3.8    True
2  Charlie   21  Physics  3.9    True
4     Evan   20  Biology  3.5    True

### Problem 9: Multi-Condition Filtering with Logical Operators

Find all students who satisfy BOTH conditions:
- `'Major'` is `'CS'`
- `'Passed'` is `True`
Remember to use the `&` operator and enclose conditions in parentheses `()`.

In [9]:
cs_passed = students_df[(students_df['Major'] == 'CS') & (students_df['Passed'] == True)]
display(cs_passed)

    Name  Age Major  GPA  Passed
0  Alice   20    CS  3.8    True

### Problem 10: Filtering with .isin() and .between()

1. Find all students whose `'Major'` is either `'Math'` or `'Physics'` using `.isin()`.
2. Find all students whose `'Age'` is between 21 and 23 (inclusive) using `.between()`.

In [10]:
math_physics = students_df[students_df['Major'].isin(['Math', 'Physics'])]
print("Math or Physics Majors:")
display(math_physics)

age_21_23 = students_df[students_df['Age'].between(21, 23)]
print("\nAge between 21 and 23:")
display(age_21_23)

Math or Physics Majors:

      Name  Age    Major  GPA  Passed
1      Bob   22     Math  3.2    True
2  Charlie   21  Physics  3.9    True

Age between 21 and 23:

      Name  Age    Major  GPA  Passed
1      Bob   22     Math  3.2    True
2  Charlie   21  Physics  3.9    True
3    Diana   23       CS  2.9   False

### Problem 11: Add Calculated Columns (Vectorized)

Add two new columns to a copy of `students_df`:
1. `'GPA_Percentage'`: Convert the 4.0 GPA scale to percentage (`GPA / 4.0 * 100`).
2. `'Honors'`: Boolean column indicating whether `GPA >= 3.8`.

In [11]:
df_copy = students_df.copy()
df_copy['GPA_Percentage'] = (df_copy['GPA'] / 4.0) * 100
df_copy['Honors'] = df_copy['GPA'] >= 3.8
display(df_copy)

      Name  Age    Major  GPA  Passed  GPA_Percentage  Honors
0    Alice   20       CS  3.8    True            95.0    True
1      Bob   22     Math  3.2    True            80.0   False
2  Charlie   21  Physics  3.9    True            97.5    True
3    Diana   23       CS  2.9   False            72.5   False
4     Evan   20  Biology  3.5    True            87.5   False

### Problem 12: Renaming Columns

Rename `'Major'` to `'Field_of_Study'` and `'Passed'` to `'Graduation_Ready'` in `students_df`.

In [12]:
df_renamed = students_df.rename(columns={
    'Major': 'Field_of_Study',
    'Passed': 'Graduation_Ready'
})
display(df_renamed.head(3))

      Name  Age Field_of_Study  GPA  Graduation_Ready
0    Alice   20             CS  3.8              True
1      Bob   22           Math  3.2              True
2  Charlie   21        Physics  3.9              True

### Problem 13: Dropping Columns Safely

Drop the `'Passed'` column from `students_df` without modifying the original in-place. Verify that the original `students_df` still has all 5 columns.

In [13]:
df_without_passed = students_df.drop(columns=['Passed'])
print("New DataFrame columns:     ", list(df_without_passed.columns))
print("Original DataFrame columns:", list(students_df.columns))

New DataFrame columns:      ['Name', 'Age', 'Major', 'GPA']
Original DataFrame columns: ['Name', 'Age', 'Major', 'GPA', 'Passed']

### Problem 14: Detecting Missing Data

Consider this dataset with missing values:
```python
exam_data = {
    'Student': ['Sam', 'Alex', 'Jordan', 'Taylor', 'Morgan'],
    'Midterm': [85.0, np.nan, 90.0, 72.0, np.nan],
    'Final': [88.0, 79.0, np.nan, 68.0, 95.0],
    'Attendance': [95, 80, 85, np.nan, 90]
}
exam_df = pd.DataFrame(exam_data)
```
1. Count total missing values (`NaN`) per column.
2. Print the total number of missing values in the entire DataFrame.

In [14]:
exam_data = {
    'Student': ['Sam', 'Alex', 'Jordan', 'Taylor', 'Morgan'],
    'Midterm': [85.0, np.nan, 90.0, 72.0, np.nan],
    'Final': [88.0, 79.0, np.nan, 68.0, 95.0],
    'Attendance': [95, 80, 85, np.nan, 90]
}
exam_df = pd.DataFrame(exam_data)

print("Missing values per column:")
print(exam_df.isna().sum())
print(f"\nTotal missing in whole table: {exam_df.isna().sum().sum()}")

Missing values per column:
Student       0
Midterm       2
Final         1
Attendance    1
dtype: int64

Total missing in whole table: 4

### Problem 15: Imputing Missing Values

Fill the missing values in `exam_df`:
1. Fill missing `'Midterm'` scores with the average (mean) of the existing Midterm scores.
2. Fill missing `'Final'` scores with the median of existing Final scores.
3. Fill missing `'Attendance'` with `100`.

In [15]:
exam_imputed = exam_df.copy()

exam_imputed['Midterm'] = exam_imputed['Midterm'].fillna(exam_imputed['Midterm'].mean())
exam_imputed['Final'] = exam_imputed['Final'].fillna(exam_imputed['Final'].median())
exam_imputed['Attendance'] = exam_imputed['Attendance'].fillna(100)

display(exam_imputed)

  Student    Midterm  Final  Attendance
0     Sam  85.000000   88.0        95.0
1    Alex  82.333333   79.0        80.0
2  Jordan  90.000000   83.5        85.0
3  Taylor  72.000000   68.0       100.0
4  Morgan  82.333333   95.0        90.0

### Problem 16: Sorting Values & Resetting Index

Using `students_df`:
1. Sort students by `'GPA'` descending (highest GPA first).
2. Reset the row index so it starts cleanly from `0, 1, 2, ...`.
3. Print the top 3 students.

In [16]:
top_students = students_df.sort_values(by='GPA', ascending=False).reset_index(drop=True)
print("Top Students by GPA:")
display(top_students.head(3))

Top Students by GPA:

      Name  Age    Major  GPA  Passed
0  Charlie   21  Physics  3.9    True
1    Alice   20       CS  3.8    True
2     Evan   20  Biology  3.5    True

### Problem 17: Summary Statistics and Value Counts

Using `students_df`:
1. Compute the mean, median, min, max, and standard deviation of `'GPA'`.
2. Count how many students belong to each `'Major'` using `.value_counts()`.
3. Calculate the percentage of students in each major.

In [17]:
print(f"GPA Mean:   {students_df['GPA'].mean():.2f}")
print(f"GPA Median: {students_df['GPA'].median():.2f}")
print(f"GPA Min:    {students_df['GPA'].min():.2f}")
print(f"GPA Max:    {students_df['GPA'].max():.2f}")
print(f"GPA Std:    {students_df['GPA'].std():.2f}")

print("\nStudent count per Major:")
print(students_df['Major'].value_counts())

print("\nMajor Percentage Share:")
print((students_df['Major'].value_counts(normalize=True) * 100).round(1))

GPA Mean:   3.46
GPA Median: 3.50
GPA Min:    2.90
GPA Max:    3.90
GPA Std:    0.42

Student count per Major:
Major
CS         2
Math       1
Physics    1
Biology    1
Name: count, dtype: int64

Major Percentage Share:
Major
CS         40.0
Math       20.0
Physics    20.0
Biology    20.0
Name: proportion, dtype: float64

### Problem 18: GroupBy Single Column Aggregation

Group `students_df` by `'Major'` and compute the average `'GPA'` and average `'Age'` for each major.

In [18]:
major_stats = students_df.groupby('Major')[['GPA', 'Age']].mean()
display(major_stats)

          GPA   Age
Major
Biology  3.50  20.0
CS       3.35  21.5
Math     3.20  22.0
Physics  3.90  21.0

### Problem 19: Named Aggregations with .groupby().agg()

Group `students_df` by `'Major'` and compute:
1. `'Student_Count'`: total number of students in that major (`count`)
2. `'Avg_GPA'`: average GPA in that major (`mean`)
3. `'Highest_GPA'`: highest GPA in that major (`max`)
Reset the index so `'Major'` becomes a regular column.

In [19]:
agg_summary = students_df.groupby('Major').agg(
    Student_Count=('Name', 'count'),
    Avg_GPA=('GPA', 'mean'),
    Highest_GPA=('GPA', 'max')
).reset_index()

display(agg_summary)

     Major  Student_Count  Avg_GPA  Highest_GPA
0  Biology              1     3.50          3.5
1       CS              2     3.35          3.8
2     Math              1     3.20          3.2
3  Physics              1     3.90          3.9

### Problem 20: String Manipulation and Datetime Parsing

Given the following enrollment log:
```python
logs_data = {
    'Raw_Student': ['  ALICE  ', 'bob smith', ' CHARLIE brown ', 'diana  '],
    'Date_Enrolled': ['2026-01-10', '2026-02-15', '2026-03-01', '2026-03-22']
}
logs_df = pd.DataFrame(logs_data)
```
1. Clean `'Raw_Student'` by trimming whitespace and capitalizing each word to Title Case.
2. Convert `'Date_Enrolled'` to datetime objects.
3. Extract the `'Month_Name'` and `'Day_of_Week'` into new columns.

In [20]:
logs_data = {
    'Raw_Student': ['  ALICE  ', 'bob smith', ' CHARLIE brown ', 'diana  '],
    'Date_Enrolled': ['2026-01-10', '2026-02-15', '2026-03-01', '2026-03-22']
}
logs_df = pd.DataFrame(logs_data)

# 1. Clean strings
logs_df['Clean_Student'] = logs_df['Raw_Student'].str.strip().str.title()

# 2. Convert to datetime
logs_df['Date_Enrolled'] = pd.to_datetime(logs_df['Date_Enrolled'])

# 3. Extract calendar features
logs_df['Month_Name'] = logs_df['Date_Enrolled'].dt.month_name()
logs_df['Day_of_Week'] = logs_df['Date_Enrolled'].dt.day_name()

display(logs_df[['Clean_Student', 'Date_Enrolled', 'Month_Name', 'Day_of_Week']])

   Clean_Student Date_Enrolled Month_Name Day_of_Week
0          Alice    2026-01-10    January    Saturday
1      Bob Smith    2026-02-15   February      Sunday
2  Charlie Brown    2026-03-01      March      Sunday
3          Diana    2026-03-22      March      Sunday